Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
SQLITE3:
  UserName: root
  Password: sqlite3
  DBName: passwd
  TablePrefix: passwd_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
  FilePath: ~/.passwd/
MySQL:
  DBType: mysql
  UserName: root
  Password: mysql
  Host: 127.0.0.1:3306
  DBName: passwd
  TablePrefix: passwd_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  UserName: root
  Password: mysql
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 604712799@qq.com
  Password: bkmfctqlgbqrbffa
  IsSSL: true
  From: ning
  To:
    - 1119148861@qq.com
Sms:
  Source: alibaba-cloud
  AccessKey: A
  AccessSecret: B